from django.db import models


# Create your models here.
# user
class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)


# vHBA sheet
class vHBA(models.Model):
    host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    device = models.CharField(verbose_name='Device', max_length=64, blank=True, null=True)
    type = models.CharField(verbose_name='Type', max_length=64, blank=True, null=True)
    status = models.CharField(verbose_name='Status', max_length=64, blank=True, null=True)
    bus = models.IntegerField(verbose_name='Bus', blank=True, null=True)
    pci = models.CharField(verbose_name='Pci', max_length=64, blank=True, null=True)
    driver = models.CharField(verbose_name='Driver', max_length=64, blank=True, null=True)
    model = models.CharField(verbose_name='Model', max_length=255, blank=True, null=True)
    wwn = models.CharField(verbose_name='Wwn', max_length=255, blank=True, null=True)
    vi_sdk_server = models.CharField(verbose_name='vCenter地址', max_length=64, blank=True, null=True)
    vi_sdk_uuid = models.CharField(verbose_name='vCenter UUID', max_length=255, blank=True, null=True)


# VM inventory
class VM(models.Model):
    vmname = models.CharField(verbose_name='vmname', max_length=64, blank=True, null=True)
    powerstate = models.CharField(verbose_name='powerstate', max_length=64, blank=True, null=True)
    template = models.CharField(verbose_name='template', max_length=64, blank=True, null=True)
    srmplaceholder = models.CharField(verbose_name='srmplaceholde', max_length=64, blank=True, null=True)
    configstatus = models.CharField(verbose_name='configstatus', max_length=64, blank=True, null=True)
    guesthostname = models.CharField(verbose_name='guesthostname', max_length=64, blank=True, null=True)
    connectionstate = models.CharField(verbose_name='connectionstate', max_length=64, blank=True, null=True)
    gueststate = models.CharField(verbose_name='gueststate', max_length=64, blank=True, null=True)
    heartbeat = models.CharField(verbose_name='heartbeat', max_length=64, blank=True, null=True)
    consolidationneeded = models.CharField(verbose_name='heartbeat', max_length=64, blank=True, null=True)
    boottime = models.CharField(verbose_name='boottime', max_length=64, blank=True, null=True)
    suspendtime = models.CharField(verbose_name='suspendtime', max_length=64, blank=True, null=True)
    createdate = models.CharField(verbose_name='createdate', max_length=64, blank=True, null=True)
    changeversion = models.CharField(verbose_name='changeversion', max_length=64, blank=True, null=True)
    cpus = models.CharField(verbose_name='cpus', max_length=64, blank=True, null=True)
    memory = models.CharField(verbose_name='memory', max_length=64, blank=True, null=True)
    nics = models.CharField(verbose_name='nics', max_length=64, blank=True, null=True)
    virtualdisks = models.CharField(verbose_name='virtualdisks', max_length=64, blank=True, null=True)
    requiredevcmodekey = models.CharField(verbose_name='requiredevcmodekey', max_length=64, blank=True, null=True)
    latencysensitivity = models.CharField(verbose_name='latencysensitivity', max_length=64, blank=True, null=True)
    enableuuid = models.CharField(verbose_name='enableuuid', max_length=64, blank=True, null=True)
    cbt = models.CharField(verbose_name='cbt', max_length=64, blank=True, null=True)
    primaryip = models.CharField(verbose_name='primaryip', max_length=64, blank=True, null=True)
    network1 = models.CharField(verbose_name='network1', max_length=64, blank=True, null=True)
    network2 = models.CharField(verbose_name='network2', max_length=64, blank=True, null=True)
    network3 = models.CharField(verbose_name='network3', max_length=64, blank=True, null=True)
    network4 = models.CharField(verbose_name='network4', max_length=64, blank=True, null=True)
    network5 = models.CharField(verbose_name='network5', max_length=64, blank=True, null=True)
    network6 = models.CharField(verbose_name='network6', max_length=64, blank=True, null=True)
    network7 = models.CharField(verbose_name='network7', max_length=64, blank=True, null=True)
    network8 = models.CharField(verbose_name='network8', max_length=64, blank=True, null=True)
    numdisplay = models.CharField(verbose_name='network8', max_length=64, blank=True, null=True)
    videoram = models.CharField(verbose_name='videoram', max_length=64, blank=True, null=True)
    resourcepool = models.CharField(verbose_name='resourcepool', max_length=64, blank=True, null=True)
    folder = models.CharField(verbose_name='folder', max_length=64, blank=True, null=True)
    vapp = models.CharField(verbose_name='vapp', max_length=64, blank=True, null=True)
    dasprotection = models.CharField(verbose_name='dasprotection', max_length=64, blank=True, null=True)
    ftstate = models.CharField(verbose_name='ftstate', max_length=64, blank=True, null=True)
    ftlatencystatus = models.CharField(verbose_name='ftlatencystatus', max_length=64, blank=True, null=True)
    ftbandwidth = models.CharField(verbose_name='ftbandwidth', max_length=64, blank=True, null=True)
    ftsecondarylatency = models.CharField(verbose_name='ftsecondarylatency', max_length=64, blank=True, null=True)
    provisioned = models.CharField(verbose_name='provisioned', max_length=64, blank=True, null=True)
    inuse = models.CharField(verbose_name='inuse', max_length=64, blank=True, null=True)
    unshared = models.CharField(verbose_name='unshared', max_length=64, blank=True, null=True)
    harestartpriority = models.CharField(verbose_name='harestartpriority', max_length=64, blank=True, null=True)
    haisolatinresponse = models.CharField(verbose_name='haisolatinresponse', max_length=64, blank=True, null=True)
    vmmonitoring = models.CharField(verbose_name='vmmonitoring', max_length=64, blank=True, null=True)
    clusterrule = models.CharField(verbose_name='clusterrule', max_length=64, blank=True, null=True)
    clusterrulename = models.CharField(verbose_name='clusterrulename', max_length=64, blank=True, null=True)
    bootrequired = models.CharField(verbose_name='bootrequired', max_length=64, blank=True, null=True)
    bootdelay = models.CharField(verbose_name='bootdelay', max_length=64, blank=True, null=True)
    bootretrydelay = models.CharField(verbose_name='bootretrydelay', max_length=64, blank=True, null=True)
    bootretryenabled = models.CharField(verbose_name='bootretryenabled', max_length=64, blank=True, null=True)
    bootbios = models.CharField(verbose_name='bootretrydelay', max_length=64, blank=True, null=True)
    firmware = models.CharField(verbose_name='firmware', max_length=64, blank=True, null=True)
    hwversion = models.CharField(verbose_name='hwversion', max_length=64, blank=True, null=True)
    hwupgradestatus = models.CharField(verbose_name='hwupgradestatus', max_length=64, blank=True, null=True)
    hwupgradepolicy = models.CharField(verbose_name='hwupgradestatus', max_length=64, blank=True, null=True)
    hwtarget = models.CharField(verbose_name='hwtarget', max_length=64, blank=True, null=True)
    path = models.CharField(verbose_name='path', max_length=256, blank=True, null=True)
    logdir = models.CharField(verbose_name='logdir', max_length=256, blank=True, null=True)
    snapshotdir = models.CharField(verbose_name='snapshotdir', max_length=256, blank=True, null=True)
    suspenddir = models.CharField(verbose_name='suspenddir', max_length=256, blank=True, null=True)
    notes = models.CharField(verbose_name='notes', max_length=512, blank=True, null=True)
    backupstatus = models.CharField(verbose_name='backupstatus', max_length=256, blank=True, null=True)
    lastbackup = models.CharField(verbose_name='lastbackup', max_length=64, blank=True, null=True)
    datacenter = models.CharField(verbose_name='datacenter', max_length=64, blank=True, null=True)
    cluster = models.CharField(verbose_name='cluster', max_length=64, blank=True, null=True)
    host = models.CharField(verbose_name='host', max_length=64, blank=True, null=True)
    os = models.CharField(verbose_name='os', max_length=64, blank=True, null=True)
    ostools = models.CharField(verbose_name='ostools', max_length=64, blank=True, null=True)
    objectid = models.CharField(verbose_name='objectid', max_length=64, blank=True, null=True)
    vmuuid = models.CharField(verbose_name='vmuuid', max_length=64, blank=True, null=True)
    visdkservertype = models.CharField(verbose_name='visdkservertype', max_length=64, blank=True, null=True)
    visdkapi = models.CharField(verbose_name='visdkapi', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    vcenteruuid = models.CharField(verbose_name='vcenteruuid', max_length=64, blank=True, null=True)


# cluster
class vCluster(models.Model):
    clustername = models.CharField(verbose_name='clustername', max_length=64, blank=True, null=True)
    configstatus = models.CharField(verbose_name='configstatus', max_length=64, blank=True, null=True)
    overallstatus = models.CharField(verbose_name='overallstatus', max_length=64, blank=True, null=True)
    numhosts = models.CharField(verbose_name='numhosts', max_length=64, blank=True, null=True)
    numeffectivehosts = models.CharField(verbose_name='numeffectivehosts', max_length=64, blank=True, null=True)
    totalcpu = models.CharField(verbose_name='totalcpu', max_length=64, blank=True, null=True)
    numcpucores = models.CharField(verbose_name='numcpucores', max_length=64, blank=True, null=True)
    numcputhreads = models.CharField(verbose_name='numcputhreads', max_length=64, blank=True, null=True)
    effectivecpu = models.CharField(verbose_name='effectivecpu', max_length=64, blank=True, null=True)
    totalmemory = models.CharField(verbose_name='totalmemory', max_length=64, blank=True, null=True)
    effectivememory = models.CharField(verbose_name='effectivememory', max_length=64, blank=True, null=True)
    numvmotions = models.CharField(verbose_name='numvmotions', max_length=64, blank=True, null=True)
    haenabled = models.CharField(verbose_name='haenabled', max_length=64, blank=True, null=True)
    failoverlevel = models.CharField(verbose_name='failoverlevel', max_length=64, blank=True, null=True)
    admissioncontrolenabled = models.CharField(verbose_name='admissioncontrolenabled', max_length=64, blank=True,
                                               null=True)
    hostmonitoring = models.CharField(verbose_name='hostmonitoring', max_length=64, blank=True, null=True)
    HBDatastoreCandidatePolicy = models.CharField(verbose_name='HBDatastoreCandidatePolicy', max_length=64, blank=True,
                                                  null=True)
    IsolationResponse = models.CharField(verbose_name='IsolationResponse', max_length=64, blank=True, null=True)
    RestartPriority = models.CharField(verbose_name='RestartPriority', max_length=64, blank=True, null=True)
    ClusterSettings = models.CharField(verbose_name='ClusterSettings', max_length=64, blank=True, null=True)
    MaxFailure = models.CharField(verbose_name='MaxFailure', max_length=64, blank=True, null=True)
    MaxFailureWin = models.CharField(verbose_name='MaxFailureWin', max_length=64, blank=True, null=True)
    FaliureInterval = models.CharField(verbose_name='FaliureInterval', max_length=64, blank=True, null=True)
    MinUpTime = models.CharField(verbose_name='MinUpTime', max_length=64, blank=True, null=True)
    VMMonitoring = models.CharField(verbose_name='VMMonitoring', max_length=64, blank=True, null=True)
    DRSenable = models.CharField(verbose_name='DRSenable', max_length=64, blank=True, null=True)
    DRSdefault = models.CharField(verbose_name='DRSdefault', max_length=64, blank=True, null=True)
    DRSvMotionRate = models.CharField(verbose_name='DRSvMotionRate', max_length=64, blank=True, null=True)
    DPMenable = models.CharField(verbose_name='DPMenable', max_length=64, blank=True, null=True)
    DPMdefault = models.CharField(verbose_name='DPMdefault', max_length=64, blank=True, null=True)
    DPMHostPower = models.CharField(verbose_name='DPMHostPower', max_length=64, blank=True, null=True)
    ObjectID = models.CharField(verbose_name='ObjectID', max_length=64, blank=True, null=True)
    visdkserver = models.CharField(verbose_name='visdkserver', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vHost
class vHost(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    ConfigStatus = models.CharField(verbose_name='ConfigStatus', max_length=64, blank=True, null=True)
    MaintenanceMode = models.CharField(verbose_name='nMaintenanceMode', max_length=64, blank=True, null=True)
    QuarantineMode = models.CharField(verbose_name='QuarantineMode', max_length=64, blank=True, null=True)
    vSANFaultDomain = models.CharField(verbose_name='vSANFaultDomain', max_length=64, blank=True, null=True)
    CPUModel = models.CharField(verbose_name='CPUModel', max_length=64, blank=True, null=True)
    Speed = models.CharField(verbose_name='Speed', max_length=64, blank=True, null=True)
    HTAvailable = models.CharField(verbose_name='HTAvailable', max_length=64, blank=True, null=True)
    HTActive = models.CharField(verbose_name='HTActive', max_length=64, blank=True, null=True)
    CPU = models.CharField(verbose_name='CPU', max_length=64, blank=True, null=True)
    CoresPerCPU = models.CharField(verbose_name='CoresPerCPU', max_length=64, blank=True, null=True)
    Cores = models.CharField(verbose_name='Cores', max_length=64, blank=True, null=True)
    CPUusage = models.CharField(verbose_name='CPUusage', max_length=64, blank=True, null=True)
    Memory = models.CharField(verbose_name='Memory', max_length=64, blank=True, null=True)
    MemoryUsage = models.CharField(verbose_name='MemoryUsage', max_length=64, blank=True, null=True)
    Console = models.CharField(verbose_name='Console', max_length=64, blank=True, null=True)
    NICs = models.CharField(verbose_name='NICs', max_length=64, blank=True, null=True)
    HBAs = models.CharField(verbose_name='HBAs', max_length=64, blank=True, null=True)
    VMsTotal = models.CharField(verbose_name='VMsTotal', max_length=64, blank=True, null=True)
    VMs = models.CharField(verbose_name='VMs', max_length=64, blank=True, null=True)
    VMsPerCore = models.CharField(verbose_name='VMsPerCore', max_length=64, blank=True, null=True)
    vCPUs = models.CharField(verbose_name='vCPUs', max_length=64, blank=True, null=True)
    vCPUsPerCore = models.CharField(verbose_name='vCPUsPerCore', max_length=64, blank=True, null=True)
    vRAM = models.CharField(verbose_name='vRAM', max_length=64, blank=True, null=True)
    VMUsedMemory = models.CharField(verbose_name='VMUsedMemory', max_length=64, blank=True, null=True)
    VMMemorySwap = models.CharField(verbose_name='VMMemorySwap', max_length=64, blank=True, null=True)
    VMMemoryBallooned = models.CharField(verbose_name='VMMemoryBallooned', max_length=64, blank=True, null=True)
    VMotionSupport = models.CharField(verbose_name='VMotionSupport', max_length=64, blank=True, null=True)
    SVMotionSupport = models.CharField(verbose_name='SVMotionSupport', max_length=64, blank=True, null=True)
    CurrentEVC = models.CharField(verbose_name='CurrentEVC', max_length=64, blank=True, null=True)
    MaxEVC = models.CharField(verbose_name='MaxEVC', max_length=64, blank=True, null=True)
    assignedLicense = models.CharField(verbose_name='assignedLicense', max_length=64, blank=True, null=True)
    ATSHB = models.CharField(verbose_name='ATS', max_length=64, blank=True, null=True)
    ATSLock = models.CharField(verbose_name='ATSLock', max_length=64, blank=True, null=True)
    CPUPowerPolicy = models.CharField(verbose_name='CPUPowerPolicy', max_length=64, blank=True, null=True)
    SupportCPUPower = models.CharField(verbose_name='SupportCPUPower', max_length=64, blank=True, null=True)
    HostPowerPolicy = models.CharField(verbose_name='HostPowerPolicy', max_length=64, blank=True, null=True)
    ESXiVersion = models.CharField(verbose_name='ESXiVersion', max_length=64, blank=True, null=True)
    BootTime = models.CharField(verbose_name='BootTime', max_length=64, blank=True, null=True)
    DNSServer = models.CharField(verbose_name='DNSServer', max_length=64, blank=True, null=True)
    DHCP = models.CharField(verbose_name='DHCP', max_length=64, blank=True, null=True)
    Domain = models.CharField(verbose_name='Domain', max_length=64, blank=True, null=True)
    DNSSearch = models.CharField(verbose_name='DNSSearch', max_length=64, blank=True, null=True)
    NTP = models.CharField(verbose_name='NTP', max_length=64, blank=True, null=True)
    NTPDRunning = models.CharField(verbose_name='NTPDRunning', max_length=64, blank=True, null=True)
    TimeZone = models.CharField(verbose_name='TimeZone', max_length=64, blank=True, null=True)
    TimeZoneName = models.CharField(verbose_name='TimeZoneName', max_length=64, blank=True, null=True)
    GMTOffset = models.CharField(verbose_name='GMTOffset', max_length=64, blank=True, null=True)
    Vendor = models.CharField(verbose_name='Vendor', max_length=64, blank=True, null=True)
    Model = models.CharField(verbose_name='Model', max_length=64, blank=True, null=True)
    SerialNumber = models.CharField(verbose_name='SerialNumber', max_length=64, blank=True, null=True)
    ServiceTag = models.CharField(verbose_name='ServiceTag', max_length=64, blank=True, null=True)
    OEMString = models.CharField(verbose_name='OEMString', max_length=64, blank=True, null=True)
    BIOSVendor = models.CharField(verbose_name='BIOSVendor', max_length=64, blank=True, null=True)
    BIOSVersion = models.CharField(verbose_name='BIOSVersion', max_length=64, blank=True, null=True)
    BIOSDate = models.CharField(verbose_name='BIOSDate', max_length=64, blank=True, null=True)
    ObjectID = models.CharField(verbose_name='ObjectID', max_length=64, blank=True, null=True)
    AutoDeployMI = models.CharField(verbose_name='AutoDeployMI', max_length=64, blank=True, null=True)
    UUID = models.CharField(verbose_name='UUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='SVMotionSupport', max_length=64, blank=True, null=True)


# vNIC
class vNIC(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    NetworkDevice = models.CharField(verbose_name='NetworkDevice', max_length=64, blank=True, null=True)
    Driver = models.CharField(verbose_name='Driver', max_length=64, blank=True, null=True)
    Speed = models.CharField(verbose_name='Speed', max_length=64, blank=True, null=True)
    Duplex = models.CharField(verbose_name='Duplex', max_length=64, blank=True, null=True)
    MAC = models.CharField(verbose_name='MAC', max_length=64, blank=True, null=True)
    Switch = models.CharField(verbose_name='Switch', max_length=64, blank=True, null=True)
    UplinkPort = models.CharField(verbose_name='UplinkPort', max_length=64, blank=True, null=True)
    PCI = models.CharField(verbose_name='PCI', max_length=64, blank=True, null=True)
    WakeOn = models.CharField(verbose_name='WakeOn', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vDatastore
class vDatastore(models.Model):
    DatastoreName = models.CharField(verbose_name='DatastoreName', max_length=64, blank=True, null=True)
    ConfigStatus = models.CharField(verbose_name='ConfigStatus', max_length=64, blank=True, null=True)
    Naa = models.CharField(verbose_name='Naa', max_length=128, blank=True, null=True)
    Access = models.CharField(verbose_name='Access', max_length=64, blank=True, null=True)
    type = models.CharField(verbose_name='type', max_length=64, blank=True, null=True)
    VMsTotal = models.CharField(verbose_name='VMsTotal', max_length=64, blank=True, null=True)
    VMs = models.CharField(verbose_name='VMs', max_length=64, blank=True, null=True)
    CapacityMiB = models.CharField(verbose_name='CapacityMiB', max_length=64, blank=True, null=True)
    ProvisionedMiB = models.CharField(verbose_name='ProvisionedMiB', max_length=64, blank=True, null=True)
    InUseMib = models.CharField(verbose_name='InUseMib', max_length=64, blank=True, null=True)
    FreeMib = models.CharField(verbose_name='FreeMib', max_length=64, blank=True, null=True)
    FreePercent = models.CharField(verbose_name='FreePercent', max_length=64, blank=True, null=True)
    SIOCenabled = models.CharField(verbose_name='SIOCenabled', max_length=64, blank=True, null=True)
    SIOCThreshold = models.CharField(verbose_name='SIOCThreshold', max_length=64, blank=True, null=True)
    HostsNum = models.CharField(verbose_name='HostsNum', max_length=64, blank=True, null=True)
    Hosts = models.CharField(verbose_name='Hosts', max_length=256, blank=True, null=True)
    ClusterName = models.CharField(verbose_name='ClusterName', max_length=64, blank=True, null=True)
    ClusterCapacityMib = models.CharField(verbose_name='ClusterCapacityMib', max_length=64, blank=True, null=True)
    ClusterFreeMib = models.CharField(verbose_name='ClusterFreeMib', max_length=64, blank=True, null=True)
    BlockSize = models.CharField(verbose_name='BlockSize', max_length=64, blank=True, null=True)
    MaxBlocks = models.CharField(verbose_name='MaxBlocks', max_length=64, blank=True, null=True)
    Extents = models.CharField(verbose_name='Extents', max_length=64, blank=True, null=True)
    MajorVersion = models.CharField(verbose_name='MajorVersion', max_length=64, blank=True, null=True)
    Version = models.CharField(verbose_name='Version', max_length=64, blank=True, null=True)
    VMFSUpgradeable = models.CharField(verbose_name='VMFSUpgradeable', max_length=64, blank=True, null=True)
    MHA = models.CharField(verbose_name='MHA', max_length=64, blank=True, null=True)
    URL = models.CharField(verbose_name='URL', max_length=128, blank=True, null=True)
    ObjectId = models.CharField(verbose_name='ObjectId', max_length=64, blank=True, null=True)
    vSphereReplication = models.CharField(verbose_name='vSphereReplication', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vMultiPath
class vMultiPath(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Datastore = models.CharField(verbose_name='Datastore', max_length=64, blank=True, null=True)
    Disk = models.CharField(verbose_name='Disk', max_length=128, blank=True, null=True)
    DisplayName = models.CharField(verbose_name='DisplayName', max_length=256, blank=True, null=True)
    Policy = models.CharField(verbose_name='Policy', max_length=64, blank=True, null=True)
    OperState = models.CharField(verbose_name='OperState', max_length=64, blank=True, null=True)
    Path1 = models.CharField(verbose_name='Path1', max_length=64, blank=True, null=True)
    Path1State = models.CharField(verbose_name='Path1State', max_length=64, blank=True, null=True)
    Path2 = models.CharField(verbose_name='Path2', max_length=64, blank=True, null=True)
    Path2State = models.CharField(verbose_name='Path2State', max_length=64, blank=True, null=True)
    Path3 = models.CharField(verbose_name='Path3', max_length=64, blank=True, null=True)
    Path3State = models.CharField(verbose_name='Path3State', max_length=64, blank=True, null=True)
    Path4 = models.CharField(verbose_name='Path4', max_length=64, blank=True, null=True)
    Path4State = models.CharField(verbose_name='Path4State', max_length=64, blank=True, null=True)
    Path5 = models.CharField(verbose_name='Path5', max_length=64, blank=True, null=True)
    Path5State = models.CharField(verbose_name='Path5State', max_length=64, blank=True, null=True)
    Path6 = models.CharField(verbose_name='Path6', max_length=64, blank=True, null=True)
    Path6State = models.CharField(verbose_name='Path6State', max_length=64, blank=True, null=True)
    Path7 = models.CharField(verbose_name='Path7', max_length=64, blank=True, null=True)
    Path7State = models.CharField(verbose_name='Path7State', max_length=64, blank=True, null=True)
    Path8 = models.CharField(verbose_name='Path8', max_length=64, blank=True, null=True)
    Path8State = models.CharField(verbose_name='Path8State', max_length=64, blank=True, null=True)
    vStorage = models.CharField(verbose_name='vStorage', max_length=64, blank=True, null=True)
    QueueDepth = models.CharField(verbose_name='QueueDepth', max_length=64, blank=True, null=True)
    Vendor = models.CharField(verbose_name='Vendor', max_length=64, blank=True, null=True)
    Model = models.CharField(verbose_name='Model', max_length=128, blank=True, null=True)
    Revision = models.CharField(verbose_name='Revision', max_length=64, blank=True, null=True)
    Level = models.CharField(verbose_name='Level', max_length=64, blank=True, null=True)
    Serial = models.CharField(verbose_name='Serial', max_length=64, blank=True, null=True)
    UUID = models.CharField(verbose_name='visdkuuid', max_length=256, blank=True, null=True)
    Objectid = models.CharField(verbose_name='Objectid', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vSC_VMK
class vSC_VMK(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    PortGroup = models.CharField(verbose_name='PortGroup', max_length=64, blank=True, null=True)
    Device = models.CharField(verbose_name='Device', max_length=64, blank=True, null=True)
    Mac = models.CharField(verbose_name='Mac', max_length=64, blank=True, null=True)
    DHCP = models.CharField(verbose_name='DHCP', max_length=64, blank=True, null=True)
    IP = models.CharField(verbose_name='IP', max_length=64, blank=True, null=True)
    IPV6 = models.CharField(verbose_name='IPV6', max_length=64, blank=True, null=True)
    SubnetMask = models.CharField(verbose_name='SubnetMask', max_length=64, blank=True, null=True)
    Gateway = models.CharField(verbose_name='Gateway', max_length=64, blank=True, null=True)
    IPV6Gateway = models.CharField(verbose_name='IPV6Gateway', max_length=64, blank=True, null=True)
    MTU = models.CharField(verbose_name='MTU', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vSwitch
class vSwitch(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Switch = models.CharField(verbose_name='Switch', max_length=64, blank=True, null=True)
    Ports = models.CharField(verbose_name='Ports', max_length=64, blank=True, null=True)
    FreePorts = models.CharField(verbose_name='FreePorts', max_length=64, blank=True, null=True)
    PromiscuousMode = models.CharField(verbose_name='PromiscuousMode', max_length=64, blank=True, null=True)
    MacChange = models.CharField(verbose_name='MacChange', max_length=64, blank=True, null=True)
    ForgedTransmits = models.CharField(verbose_name='ForgedTransmits', max_length=64, blank=True, null=True)
    TrafficShaping = models.CharField(verbose_name='TrafficShaping', max_length=64, blank=True, null=True)
    Width = models.CharField(verbose_name='Width', max_length=64, blank=True, null=True)
    Peak = models.CharField(verbose_name='Peak', max_length=64, blank=True, null=True)
    Burst = models.CharField(verbose_name='Burst', max_length=64, blank=True, null=True)
    Policy = models.CharField(verbose_name='Policy', max_length=64, blank=True, null=True)
    ReversePolicy = models.CharField(verbose_name='ReversePolicy', max_length=64, blank=True, null=True)
    NotifySwitch = models.CharField(verbose_name='NotifySwitch', max_length=64, blank=True, null=True)
    RollingOrder = models.CharField(verbose_name='RollingOrder', max_length=64, blank=True, null=True)
    Offload = models.CharField(verbose_name='Offload', max_length=64, blank=True, null=True)
    TSO = models.CharField(verbose_name='TSO', max_length=64, blank=True, null=True)
    ZeroCopy = models.CharField(verbose_name='ZeroCopy', max_length=64, blank=True, null=True)
    MTU = models.CharField(verbose_name='MTU', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vPort
class vPort(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    PortGroup = models.CharField(verbose_name='PortGroup', max_length=64, blank=True, null=True)
    Switch = models.CharField(verbose_name='Switch', max_length=64, blank=True, null=True)
    VLAN = models.CharField(verbose_name='VLAN', max_length=64, blank=True, null=True)
    PromiscuousMode = models.CharField(verbose_name='PromiscuousMode', max_length=64, blank=True, null=True)
    MacChange = models.CharField(verbose_name='MacChange', max_length=64, blank=True, null=True)
    ForgedTransmits = models.CharField(verbose_name='ForgedTransmits', max_length=64, blank=True, null=True)
    TrafficShaping = models.CharField(verbose_name='TrafficShaping', max_length=64, blank=True, null=True)
    Width = models.CharField(verbose_name='Width', max_length=64, blank=True, null=True)
    Peak = models.CharField(verbose_name='Peak', max_length=64, blank=True, null=True)
    Burst = models.CharField(verbose_name='Burst', max_length=64, blank=True, null=True)
    Policy = models.CharField(verbose_name='Policy', max_length=64, blank=True, null=True)
    ReversePolicy = models.CharField(verbose_name='ReversePolicy', max_length=64, blank=True, null=True)
    NotifySwitch = models.CharField(verbose_name='NotifySwitch', max_length=64, blank=True, null=True)
    RollingOrder = models.CharField(verbose_name='RollingOrder', max_length=64, blank=True, null=True)
    Offload = models.CharField(verbose_name='Offload', max_length=64, blank=True, null=True)
    TSO = models.CharField(verbose_name='TSO', max_length=64, blank=True, null=True)
    ZeroCopy = models.CharField(verbose_name='ZeroCopy', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# dvSwitch
class dvSwitch(models.Model):
    Switch = models.CharField(verbose_name='Switch', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    DVS = models.CharField(verbose_name='DVS', max_length=64, blank=True, null=True)
    Vendor = models.CharField(verbose_name='Vendor', max_length=128, blank=True, null=True)
    Version = models.CharField(verbose_name='Version', max_length=256, blank=True, null=True)
    Description = models.CharField(verbose_name='Description', max_length=64, blank=True, null=True)
    Created = models.CharField(verbose_name='Created', max_length=64, blank=True, null=True)
    HostMembers = models.CharField(verbose_name='HostMembers', max_length=1024, blank=True, null=True)
    MaxPorts = models.CharField(verbose_name='MaxPorts', max_length=64, blank=True, null=True)
    Ports = models.CharField(verbose_name='Ports', max_length=64, blank=True, null=True)
    VMs = models.CharField(verbose_name='VMs', max_length=64, blank=True, null=True)
    InTrafficShaping = models.CharField(verbose_name='InTrafficShaping', max_length=64, blank=True, null=True)
    InAvg = models.CharField(verbose_name='InAvg', max_length=64, blank=True, null=True)
    InPeak = models.CharField(verbose_name='InPeak', max_length=64, blank=True, null=True)
    InBurst = models.CharField(verbose_name='InBurst', max_length=64, blank=True, null=True)
    OutTrafficShaping = models.CharField(verbose_name='OutTrafficShaping', max_length=64, blank=True, null=True)
    OutAvg = models.CharField(verbose_name='OutAvg', max_length=64, blank=True, null=True)
    OutPeak = models.CharField(verbose_name='OutPeak', max_length=64, blank=True, null=True)
    OutBurst = models.CharField(verbose_name='OutBurst', max_length=64, blank=True, null=True)
    CDPType = models.CharField(verbose_name='CDPType', max_length=64, blank=True, null=True)
    CDPOperation = models.CharField(verbose_name='CDPOperation', max_length=64, blank=True, null=True)
    LACPname = models.CharField(verbose_name='LACPname', max_length=64, blank=True, null=True)
    LACPmode = models.CharField(verbose_name='LACPmode', max_length=64, blank=True, null=True)
    LACPLB = models.CharField(verbose_name='LACPLB', max_length=64, blank=True, null=True)
    MaxMTU = models.CharField(verbose_name='MaxMTU', max_length=64, blank=True, null=True)
    Contact = models.CharField(verbose_name='Contact', max_length=64, blank=True, null=True)
    AdminName = models.CharField(verbose_name='AdminName', max_length=64, blank=True, null=True)
    ObjectID = models.CharField(verbose_name='ObjectID', max_length=128, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# dvPort
class dvPort(models.Model):
    Port = models.CharField(verbose_name='Port', max_length=64, blank=True, null=True)
    Switch = models.CharField(verbose_name='Switch', max_length=64, blank=True, null=True)
    Type = models.CharField(verbose_name='Type', max_length=64, blank=True, null=True)
    Ports = models.CharField(verbose_name='Ports', max_length=64, blank=True, null=True)
    VLAN = models.CharField(verbose_name='VLAN', max_length=64, blank=True, null=True)
    Speed = models.CharField(verbose_name='Speed', max_length=256, blank=True, null=True)
    FullDuplex = models.CharField(verbose_name='FullDuplex', max_length=64, blank=True, null=True)
    Blocked = models.CharField(verbose_name='Blocked', max_length=64, blank=True, null=True)
    AllowPromiscuous = models.CharField(verbose_name='AllowPromiscuous', max_length=1024, blank=True, null=True)
    MacChange = models.CharField(verbose_name='MacChange', max_length=64, blank=True, null=True)
    ActiveUplink = models.CharField(verbose_name='ActiveUplink', max_length=64, blank=True, null=True)
    StandbyUplink = models.CharField(verbose_name='StandbyUplink', max_length=64, blank=True, null=True)
    Policy = models.CharField(verbose_name='Policy', max_length=64, blank=True, null=True)
    ForgedTransmits = models.CharField(verbose_name='ForgedTransmits', max_length=64, blank=True, null=True)
    InTrafficShaping = models.CharField(verbose_name='InTrafficShaping', max_length=64, blank=True, null=True)
    InAvg = models.CharField(verbose_name='InAvg', max_length=64, blank=True, null=True)
    InPeak = models.CharField(verbose_name='InPeak', max_length=64, blank=True, null=True)
    InBurst = models.CharField(verbose_name='InBurst', max_length=64, blank=True, null=True)
    OutTrafficShaping = models.CharField(verbose_name='OutTrafficShaping', max_length=64, blank=True, null=True)
    OutAvg = models.CharField(verbose_name='OutAvg', max_length=64, blank=True, null=True)
    OutPeak = models.CharField(verbose_name='OutPeak', max_length=64, blank=True, null=True)
    OutBurst = models.CharField(verbose_name='OutBurst', max_length=64, blank=True, null=True)
    ReversePolicy = models.CharField(verbose_name='ReversePolicy', max_length=64, blank=True, null=True)
    NotifySwitch = models.CharField(verbose_name='NotifySwitch', max_length=64, blank=True, null=True)
    RollingOrder = models.CharField(verbose_name='RollingOrder', max_length=64, blank=True, null=True)
    CheckBeacon = models.CharField(verbose_name='CheckBeacon', max_length=64, blank=True, null=True)
    LivePortMoving = models.CharField(verbose_name='LivePortMoving', max_length=64, blank=True, null=True)
    checkDuplex = models.CharField(verbose_name='checkDuplex', max_length=64, blank=True, null=True)
    checkError = models.CharField(verbose_name='checkError', max_length=64, blank=True, null=True)
    checkSpeed = models.CharField(verbose_name='checkSpeed', max_length=64, blank=True, null=True)
    Percen = models.CharField(verbose_name='Percen', max_length=64, blank=True, null=True)
    BlockOverride = models.CharField(verbose_name='BlockOverride', max_length=64, blank=True, null=True)
    ConfigReset = models.CharField(verbose_name='ConfigReset', max_length=64, blank=True, null=True)
    ShapingOverride = models.CharField(verbose_name='ShapingOverride', max_length=64, blank=True, null=True)
    VendorConfigOverride = models.CharField(verbose_name='VendorConfigOverride', max_length=64, blank=True, null=True)
    PolicyOverride = models.CharField(verbose_name='PolicyOverride', max_length=64, blank=True, null=True)
    TeamingOverride = models.CharField(verbose_name='TeamingOverride', max_length=64, blank=True, null=True)
    VLANOverride = models.CharField(verbose_name='VLANOverride', max_length=64, blank=True, null=True)
    ObjectID = models.CharField(verbose_name='ObjectID', max_length=128, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vHealth
class vHealth(models.Model):
    Name = models.CharField(verbose_name='Name', max_length=512, blank=True, null=True)
    Message = models.CharField(verbose_name='Datacenter', max_length=512, blank=True, null=True)
    MessageType = models.CharField(verbose_name='MessageType', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vTools
class vTools(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Template = models.CharField(verbose_name='Template', max_length=64, blank=True, null=True)
    SRMPlaceholder = models.CharField(verbose_name='SRMPlaceholder', max_length=64, blank=True, null=True)
    VMVersion = models.CharField(verbose_name='VMVersion', max_length=64, blank=True, null=True)
    Tools = models.CharField(verbose_name='Tools', max_length=64, blank=True, null=True)
    ToolsVersion = models.CharField(verbose_name='ToolsVersion', max_length=64, blank=True, null=True)
    RequiredVersion = models.CharField(verbose_name='RequiredVersion', max_length=64, blank=True, null=True)
    Upgradeable = models.CharField(verbose_name='Upgradeable', max_length=64, blank=True, null=True)
    UpgradePolicy = models.CharField(verbose_name='UpgradePolicy', max_length=64, blank=True, null=True)
    SyncTime = models.CharField(verbose_name='SyncTime', max_length=64, blank=True, null=True)
    AppStatus = models.CharField(verbose_name='AppStatus', max_length=64, blank=True, null=True)
    HeartbeatStatus = models.CharField(verbose_name='HeartbeatStatus', max_length=64, blank=True, null=True)
    KernelCrashState = models.CharField(verbose_name='KernelCrashState', max_length=64, blank=True, null=True)
    OperationReady = models.CharField(verbose_name='OperationReady', max_length=64, blank=True, null=True)
    StateChangeSupport = models.CharField(verbose_name='StateChangeSupport', max_length=256, blank=True, null=True)
    InteractiveGuest = models.CharField(verbose_name='InteractiveGuest', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=256, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=128, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=64, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMRef = models.CharField(verbose_name='VMRef', max_length=128, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vCD
class vCD(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Template = models.CharField(verbose_name='Template', max_length=64, blank=True, null=True)
    SRMPlaceholder = models.CharField(verbose_name='SRMPlaceholder', max_length=64, blank=True, null=True)
    DeviceNode = models.CharField(verbose_name='DeviceNode', max_length=64, blank=True, null=True)
    Connected = models.CharField(verbose_name='Connected', max_length=256, blank=True, null=True)
    StartsConnected = models.CharField(verbose_name='StartsConnected', max_length=64, blank=True, null=True)
    DeviceType = models.CharField(verbose_name='DeviceType', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=512, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=256, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=64, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=256, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMRef = models.CharField(verbose_name='VMRef', max_length=64, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vSnapshot
class vSnapshot(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Name = models.CharField(verbose_name='Name', max_length=64, blank=True, null=True)
    Description = models.CharField(verbose_name='Description', max_length=256, blank=True, null=True)
    Date = models.CharField(verbose_name='Date', max_length=64, blank=True, null=True)
    Filename = models.CharField(verbose_name='Filename', max_length=256, blank=True, null=True)
    Size = models.CharField(verbose_name='Size', max_length=64, blank=True, null=True)
    SizeTotal = models.CharField(verbose_name='SizeTotal', max_length=64, blank=True, null=True)
    Quiesced = models.CharField(verbose_name='Quiesced', max_length=64, blank=True, null=True)
    State = models.CharField(verbose_name='State', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    AppStatus = models.CharField(verbose_name='AppStatus', max_length=64, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=512, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=64, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=64, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vPartition
class vPartition(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Template = models.CharField(verbose_name='Template', max_length=64, blank=True, null=True)
    SRMPlaceholder = models.CharField(verbose_name='SRMPlaceholder', max_length=256, blank=True, null=True)
    DiskKey = models.CharField(verbose_name='DiskKey', max_length=64, blank=True, null=True)
    Disk = models.CharField(verbose_name='Disk', max_length=256, blank=True, null=True)
    Capacity = models.CharField(verbose_name='Capacity', max_length=64, blank=True, null=True)
    Consumed = models.CharField(verbose_name='Consumed', max_length=64, blank=True, null=True)
    free = models.CharField(verbose_name='free', max_length=64, blank=True, null=True)
    freerate = models.CharField(verbose_name='freerate', max_length=64, blank=True, null=True)
    InternalSort = models.CharField(verbose_name='InternalSort', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=512, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=64, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=64, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vNetwork
class vNetwork(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Template = models.CharField(verbose_name='Template', max_length=64, blank=True, null=True)
    SRMPlaceholder = models.CharField(verbose_name='SRMPlaceholder', max_length=256, blank=True, null=True)
    NICLabel = models.CharField(verbose_name='NICLabel', max_length=64, blank=True, null=True)
    Adapter = models.CharField(verbose_name='Adapter', max_length=256, blank=True, null=True)
    Network = models.CharField(verbose_name='Network', max_length=64, blank=True, null=True)
    Switch = models.CharField(verbose_name='Switch', max_length=64, blank=True, null=True)
    Connected = models.CharField(verbose_name='Connected', max_length=64, blank=True, null=True)
    StartsConnected = models.CharField(verbose_name='StartsConnected', max_length=64, blank=True, null=True)
    MAC = models.CharField(verbose_name='MAC', max_length=64, blank=True, null=True)
    Type = models.CharField(verbose_name='Type', max_length=64, blank=True, null=True)
    IPV4 = models.CharField(verbose_name='IPV4', max_length=128, blank=True, null=True)
    IPV6 = models.CharField(verbose_name='IPV6', max_length=128, blank=True, null=True)
    DirectPathIO = models.CharField(verbose_name='DirectPathIO', max_length=128, blank=True, null=True)
    InternalSort = models.CharField(verbose_name='InternalSort', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=512, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=64, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=64, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vDisk
class vDisk(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Template = models.CharField(verbose_name='Template', max_length=64, blank=True, null=True)
    SRMPlaceholder = models.CharField(verbose_name='SRMPlaceholder', max_length=256, blank=True, null=True)
    Disk = models.CharField(verbose_name='Disk', max_length=64, blank=True, null=True)
    DiskKey = models.CharField(verbose_name='DiskKey', max_length=64, blank=True, null=True)
    DiskPath = models.CharField(verbose_name='DiskPath', max_length=128, blank=True, null=True)
    Capacity = models.CharField(verbose_name='Capacity', max_length=64, blank=True, null=True)
    Raw = models.CharField(verbose_name='Raw', max_length=64, blank=True, null=True)
    DiskMode = models.CharField(verbose_name='DiskMode', max_length=64, blank=True, null=True)
    Thin = models.CharField(verbose_name='Thin', max_length=64, blank=True, null=True)
    EagerlyScrub = models.CharField(verbose_name='EagerlyScrub', max_length=64, blank=True, null=True)
    Split = models.CharField(verbose_name='Split', max_length=128, blank=True, null=True)
    WriteThrough = models.CharField(verbose_name='WriteThrough', max_length=128, blank=True, null=True)
    Level = models.CharField(verbose_name='Level', max_length=128, blank=True, null=True)
    Shares = models.CharField(verbose_name='Shares', max_length=64, blank=True, null=True)
    Reservation = models.CharField(verbose_name='Reservation', max_length=512, blank=True, null=True)
    LimitUse = models.CharField(verbose_name='LimitUse', max_length=64, blank=True, null=True)
    Controller = models.CharField(verbose_name='Controller', max_length=64, blank=True, null=True)
    Label = models.CharField(verbose_name='Label', max_length=64, blank=True, null=True)
    SCSIUnit = models.CharField(verbose_name='SCSIUnit', max_length=64, blank=True, null=True)
    Unit = models.CharField(verbose_name='Level', max_length=64, blank=True, null=True)
    SharedBus = models.CharField(verbose_name='SharedBus', max_length=64, blank=True, null=True)
    Path = models.CharField(verbose_name='Path', max_length=512, blank=True, null=True)
    RawLUNid = models.CharField(verbose_name='RawLUNid', max_length=64, blank=True, null=True)
    RawCompMode = models.CharField(verbose_name='RawCompMode', max_length=64, blank=True, null=True)
    InternalSort = models.CharField(verbose_name='InternalSort', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=512, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=64, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=64, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vCPU
class vCPU(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Template = models.CharField(verbose_name='Template', max_length=64, blank=True, null=True)
    SRMPlaceholder = models.CharField(verbose_name='SRMPlaceholder', max_length=256, blank=True, null=True)
    CPUs = models.CharField(verbose_name='CPUs', max_length=64, blank=True, null=True)
    Sockets = models.CharField(verbose_name='Sockets', max_length=64, blank=True, null=True)
    Cores = models.CharField(verbose_name='Cores', max_length=64, blank=True, null=True)
    Max = models.CharField(verbose_name='Max', max_length=64, blank=True, null=True)
    Overrall = models.CharField(verbose_name='Overrall', max_length=64, blank=True, null=True)
    Level = models.CharField(verbose_name='Level', max_length=64, blank=True, null=True)
    Shares = models.CharField(verbose_name='Shares', max_length=64, blank=True, null=True)
    Reservation = models.CharField(verbose_name='Reservation', max_length=64, blank=True, null=True)
    Entitlement = models.CharField(verbose_name='Entitlement', max_length=64, blank=True, null=True)
    DRSEntitlement = models.CharField(verbose_name='DRSEntitlement', max_length=128, blank=True, null=True)
    LimitUse = models.CharField(verbose_name='LimitUse', max_length=64, blank=True, null=True)
    HotAdd = models.CharField(verbose_name='HotAdd', max_length=64, blank=True, null=True)
    HotRemove = models.CharField(verbose_name='HotRemove', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=512, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=64, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=64, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)


# vMemory
class vMemory(models.Model):
    VM = models.CharField(verbose_name='VM', max_length=64, blank=True, null=True)
    Powerstate = models.CharField(verbose_name='Powerstate', max_length=64, blank=True, null=True)
    Template = models.CharField(verbose_name='Template', max_length=64, blank=True, null=True)
    SRMPlaceholder = models.CharField(verbose_name='SRMPlaceholder', max_length=256, blank=True, null=True)
    SizeMiB = models.CharField(verbose_name='SizeMiB', max_length=64, blank=True, null=True)
    MemoryResevation = models.CharField(verbose_name='MemoryResevation', max_length=64, blank=True, null=True)
    Overhead = models.CharField(verbose_name='Overhead', max_length=64, blank=True, null=True)
    Max = models.CharField(verbose_name='Max', max_length=64, blank=True, null=True)
    Consumed = models.CharField(verbose_name='Consumed', max_length=64, blank=True, null=True)
    ConsumedOverhead = models.CharField(verbose_name='ConsumedOverhead', max_length=64, blank=True, null=True)
    Private = models.CharField(verbose_name='Private', max_length=64, blank=True, null=True)
    Shared = models.CharField(verbose_name='Shared', max_length=64, blank=True, null=True)
    Swapped = models.CharField(verbose_name='Swapped', max_length=64, blank=True, null=True)
    Ballooned = models.CharField(verbose_name='Ballooned', max_length=128, blank=True, null=True)
    Active = models.CharField(verbose_name='Active', max_length=64, blank=True, null=True)
    Entitlement = models.CharField(verbose_name='Entitlement', max_length=64, blank=True, null=True)
    DRSEntitlement = models.CharField(verbose_name='DRSEntitlement', max_length=64, blank=True, null=True)
    Level = models.CharField(verbose_name='Level', max_length=64, blank=True, null=True)
    Shares = models.CharField(verbose_name='Shares', max_length=64, blank=True, null=True)
    Resevation = models.CharField(verbose_name='Resevation', max_length=64, blank=True, null=True)
    LimitUse = models.CharField(verbose_name='LimitUse', max_length=64, blank=True, null=True)
    HotAdd = models.CharField(verbose_name='HotAdd', max_length=64, blank=True, null=True)
    Annotation = models.CharField(verbose_name='Annotation', max_length=512, blank=True, null=True)
    BackupStatus = models.CharField(verbose_name='BackupStatus', max_length=512, blank=True, null=True)
    LastBackup = models.CharField(verbose_name='LastBackup', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Folder = models.CharField(verbose_name='Folder', max_length=64, blank=True, null=True)
    OSconfig = models.CharField(verbose_name='OSconfig', max_length=64, blank=True, null=True)
    OSconfigToVMwaretools = models.CharField(verbose_name='OSconfigToVMwaretools', max_length=64, blank=True, null=True)
    VMId = models.CharField(verbose_name='VMId', max_length=64, blank=True, null=True)
    VMUUID = models.CharField(verbose_name='VMUUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)