from django.db import models


# Create your models here.
# user
class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)


# vHBA sheet
class vHBA(models.Model):
    host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    device = models.CharField(verbose_name='Device', max_length=64, blank=True, null=True)
    type = models.CharField(verbose_name='Type', max_length=64, blank=True, null=True)
    status = models.CharField(verbose_name='Status', max_length=64, blank=True, null=True)
    bus = models.IntegerField(verbose_name='Bus', blank=True, null=True)
    pci = models.CharField(verbose_name='Pci', max_length=64, blank=True, null=True)
    driver = models.CharField(verbose_name='Driver', max_length=64, blank=True, null=True)
    model = models.CharField(verbose_name='Model', max_length=255, blank=True, null=True)
    wwn = models.CharField(verbose_name='Wwn', max_length=255, blank=True, null=True)
    vi_sdk_server = models.CharField(verbose_name='vCenter地址', max_length=64, blank=True, null=True)
    vi_sdk_uuid = models.CharField(verbose_name='vCenter UUID', max_length=255, blank=True, null=True)


# VM inventory
class VM(models.Model):
    vmname = models.CharField(verbose_name='vmname', max_length=64, blank=True, null=True)
    powerstate = models.CharField(verbose_name='powerstate', max_length=64, blank=True, null=True)
    template = models.CharField(verbose_name='template', max_length=64, blank=True, null=True)
    srmplaceholder = models.CharField(verbose_name='srmplaceholde', max_length=64, blank=True, null=True)
    configstatus = models.CharField(verbose_name='configstatus', max_length=64, blank=True, null=True)
    guesthostname = models.CharField(verbose_name='guesthostname', max_length=64, blank=True, null=True)
    connectionstate = models.CharField(verbose_name='connectionstate', max_length=64, blank=True, null=True)
    gueststate = models.CharField(verbose_name='gueststate', max_length=64, blank=True, null=True)
    heartbeat = models.CharField(verbose_name='heartbeat', max_length=64, blank=True, null=True)
    consolidationneeded = models.CharField(verbose_name='heartbeat', max_length=64, blank=True, null=True)
    boottime = models.CharField(verbose_name='boottime', max_length=64, blank=True, null=True)
    suspendtime = models.CharField(verbose_name='suspendtime', max_length=64, blank=True, null=True)
    createdate = models.CharField(verbose_name='createdate', max_length=64,blank=True, null=True)
    changeversion = models.CharField(verbose_name='changeversion', max_length=64, blank=True, null=True)
    cpus = models.CharField(verbose_name='cpus', max_length=64, blank=True, null=True)
    memory = models.CharField(verbose_name='memory', max_length=64, blank=True, null=True)
    nics = models.CharField(verbose_name='nics', max_length=64, blank=True, null=True)
    virtualdisks = models.CharField(verbose_name='virtualdisks', max_length=64, blank=True, null=True)
    requiredevcmodekey = models.CharField(verbose_name='requiredevcmodekey', max_length=64, blank=True, null=True)
    latencysensitivity = models.CharField(verbose_name='latencysensitivity', max_length=64, blank=True, null=True)
    enableuuid = models.CharField(verbose_name='enableuuid', max_length=64, blank=True, null=True)
    cbt = models.CharField(verbose_name='cbt', max_length=64, blank=True, null=True)
    primaryip = models.CharField(verbose_name='primaryip', max_length=64, blank=True, null=True)
    network1 = models.CharField(verbose_name='network1', max_length=64, blank=True, null=True)
    network2 = models.CharField(verbose_name='network2', max_length=64, blank=True, null=True)
    network3 = models.CharField(verbose_name='network3', max_length=64, blank=True, null=True)
    network4 = models.CharField(verbose_name='network4', max_length=64, blank=True, null=True)
    network5 = models.CharField(verbose_name='network5', max_length=64, blank=True, null=True)
    network6 = models.CharField(verbose_name='network6', max_length=64, blank=True, null=True)
    network7 = models.CharField(verbose_name='network7', max_length=64, blank=True, null=True)
    network8 = models.CharField(verbose_name='network8', max_length=64, blank=True, null=True)
    numdisplay = models.CharField(verbose_name='network8', max_length=64, blank=True, null=True)
    videoram = models.CharField(verbose_name='videoram', max_length=64, blank=True, null=True)
    resourcepool = models.CharField(verbose_name='resourcepool', max_length=64, blank=True, null=True)
    folder = models.CharField(verbose_name='folder', max_length=64, blank=True, null=True)
    vapp = models.CharField(verbose_name='vapp', max_length=64, blank=True, null=True)
    dasprotection = models.CharField(verbose_name='dasprotection', max_length=64, blank=True, null=True)
    ftstate = models.CharField(verbose_name='ftstate', max_length=64, blank=True, null=True)
    ftlatencystatus = models.CharField(verbose_name='ftlatencystatus', max_length=64, blank=True, null=True)
    ftbandwidth = models.CharField(verbose_name='ftbandwidth', max_length=64, blank=True, null=True)
    ftsecondarylatency = models.CharField(verbose_name='ftsecondarylatency', max_length=64, blank=True, null=True)
    provisioned = models.CharField(verbose_name='provisioned', max_length=64, blank=True, null=True)
    inuse = models.CharField(verbose_name='inuse', max_length=64, blank=True, null=True)
    unshared = models.CharField(verbose_name='unshared', max_length=64, blank=True, null=True)
    harestartpriority = models.CharField(verbose_name='harestartpriority', max_length=64, blank=True, null=True)
    haisolatinresponse = models.CharField(verbose_name='haisolatinresponse', max_length=64, blank=True, null=True)
    vmmonitoring = models.CharField(verbose_name='vmmonitoring', max_length=64, blank=True, null=True)
    clusterrule = models.CharField(verbose_name='clusterrule', max_length=64, blank=True, null=True)
    clusterrulename = models.CharField(verbose_name='clusterrulename', max_length=64, blank=True, null=True)
    installbootrequired = models.CharField(verbose_name='installbootrequired', max_length=64, blank=True, null=True)
    bootdelay =  models.CharField(verbose_name='bootdelay', max_length=64, blank=True, null=True)
    bootretrydelay = models.CharField(verbose_name='bootretrydelay', max_length=64, blank=True, null=True)
    bootretryenabled = models.CharField(verbose_name='bootretryenabled', max_length=64, blank=True, null=True)
    bootbios = models.CharField(verbose_name='bootretrydelay', max_length=64, blank=True, null=True)
    firmware = models.CharField(verbose_name='firmware', max_length=64, blank=True, null=True)
    hwversion = models.CharField(verbose_name='hwversion', max_length=64, blank=True, null=True)
    hwupgradestatus = models.CharField(verbose_name='hwupgradestatus', max_length=64, blank=True, null=True)
    hwupgradepolicy = models.CharField(verbose_name='hwupgradestatus', max_length=64, blank=True, null=True)
    hwtarget = models.CharField(verbose_name='hwtarget', max_length=64, blank=True, null=True)
    path = models.CharField(verbose_name='path', max_length=256, blank=True, null=True)
    logdir = models.CharField(verbose_name='logdir', max_length=256, blank=True, null=True)
    snapshotdir = models.CharField(verbose_name='snapshotdir', max_length=256, blank=True, null=True)
    suspenddir = models.CharField(verbose_name='suspenddir', max_length=256, blank=True, null=True)
    notes = models.CharField(verbose_name='notes', max_length=512, blank=True, null=True)
    datacenter = models.CharField(verbose_name='datacenter', max_length=64, blank=True, null=True)
    cluster = models.CharField(verbose_name='cluster', max_length=64, blank=True, null=True)
    host = models.CharField(verbose_name='host', max_length=64, blank=True, null=True)
    os = models.CharField(verbose_name='os', max_length=64, blank=True, null=True)
    ostools = models.CharField(verbose_name='ostools', max_length=64, blank=True, null=True)
    objectid = models.CharField(verbose_name='objectid', max_length=64, blank=True, null=True)
    uuid = models.CharField(verbose_name='uuid', max_length=64, blank=True, null=True)
    visdkservertype = models.CharField(verbose_name='visdkservertype', max_length=64, blank=True, null=True)
    visdkapi = models.CharField(verbose_name='visdkapi', max_length=64, blank=True, null=True)
    vmtag = models.CharField(verbose_name='vmtag', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    vcenteruuid = models.CharField(verbose_name='vcenteruuid', max_length=64, blank=True, null=True)