from django.db import models


# Create your models here.
# user
class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)


# vHBA sheet
class vHBA(models.Model):
    host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    device = models.CharField(verbose_name='Device', max_length=64, blank=True, null=True)
    type = models.CharField(verbose_name='Type', max_length=64, blank=True, null=True)
    status = models.CharField(verbose_name='Status', max_length=64, blank=True, null=True)
    bus = models.IntegerField(verbose_name='Bus', blank=True, null=True)
    pci = models.CharField(verbose_name='Pci', max_length=64, blank=True, null=True)
    driver = models.CharField(verbose_name='Driver', max_length=64, blank=True, null=True)
    model = models.CharField(verbose_name='Model', max_length=255, blank=True, null=True)
    wwn = models.CharField(verbose_name='Wwn', max_length=255, blank=True, null=True)
    vi_sdk_server = models.CharField(verbose_name='vCenter地址', max_length=64, blank=True, null=True)
    vi_sdk_uuid = models.CharField(verbose_name='vCenter UUID', max_length=255, blank=True, null=True)

# VM inventory
class VM(models.Model):
    vmname = models.CharField(verbose_name='vmname', max_length=64, blank=True, null=True)
    powerstate = models.CharField(verbose_name='powerstate', max_length=64, blank=True, null=True)
    template = models.CharField(verbose_name='template', max_length=64, blank=True, null=True)
    srmplaceholder = models.CharField(verbose_name='srmplaceholde', max_length=64, blank=True, null=True)
    configstatus = models.CharField(verbose_name='configstatus', max_length=64, blank=True, null=True)
    guesthostname = models.CharField(verbose_name='guesthostname', max_length=64, blank=True, null=True)
    connectionstate = models.CharField(verbose_name='connectionstate', max_length=64, blank=True, null=True)
    gueststate = models.CharField(verbose_name='gueststate', max_length=64, blank=True, null=True)
    heartbeat = models.CharField(verbose_name='heartbeat', max_length=64, blank=True, null=True)
    consolidationneeded = models.CharField(verbose_name='heartbeat', max_length=64, blank=True, null=True)
    boottime = models.CharField(verbose_name='boottime', max_length=64, blank=True, null=True)
    suspendtime = models.CharField(verbose_name='suspendtime', max_length=64, blank=True, null=True)
    createdate = models.CharField(verbose_name='createdate', max_length=64, blank=True, null=True)
    changeversion = models.CharField(verbose_name='changeversion', max_length=64, blank=True, null=True)
    cpus = models.CharField(verbose_name='cpus', max_length=64, blank=True, null=True)
    memory = models.CharField(verbose_name='memory', max_length=64, blank=True, null=True)
    nics = models.CharField(verbose_name='nics', max_length=64, blank=True, null=True)
    virtualdisks = models.CharField(verbose_name='virtualdisks', max_length=64, blank=True, null=True)
    requiredevcmodekey = models.CharField(verbose_name='requiredevcmodekey', max_length=64, blank=True, null=True)
    latencysensitivity = models.CharField(verbose_name='latencysensitivity', max_length=64, blank=True, null=True)
    enableuuid = models.CharField(verbose_name='enableuuid', max_length=64, blank=True, null=True)
    cbt = models.CharField(verbose_name='cbt', max_length=64, blank=True, null=True)
    primaryip = models.CharField(verbose_name='primaryip', max_length=64, blank=True, null=True)
    network1 = models.CharField(verbose_name='network1', max_length=64, blank=True, null=True)
    network2 = models.CharField(verbose_name='network2', max_length=64, blank=True, null=True)
    network3 = models.CharField(verbose_name='network3', max_length=64, blank=True, null=True)
    network4 = models.CharField(verbose_name='network4', max_length=64, blank=True, null=True)
    network5 = models.CharField(verbose_name='network5', max_length=64, blank=True, null=True)
    network6 = models.CharField(verbose_name='network6', max_length=64, blank=True, null=True)
    network7 = models.CharField(verbose_name='network7', max_length=64, blank=True, null=True)
    network8 = models.CharField(verbose_name='network8', max_length=64, blank=True, null=True)
    numdisplay = models.CharField(verbose_name='network8', max_length=64, blank=True, null=True)
    videoram = models.CharField(verbose_name='videoram', max_length=64, blank=True, null=True)
    resourcepool = models.CharField(verbose_name='resourcepool', max_length=64, blank=True, null=True)
    folder = models.CharField(verbose_name='folder', max_length=64, blank=True, null=True)
    vapp = models.CharField(verbose_name='vapp', max_length=64, blank=True, null=True)
    dasprotection = models.CharField(verbose_name='dasprotection', max_length=64, blank=True, null=True)
    ftstate = models.CharField(verbose_name='ftstate', max_length=64, blank=True, null=True)
    ftlatencystatus = models.CharField(verbose_name='ftlatencystatus', max_length=64, blank=True, null=True)
    ftbandwidth = models.CharField(verbose_name='ftbandwidth', max_length=64, blank=True, null=True)
    ftsecondarylatency = models.CharField(verbose_name='ftsecondarylatency', max_length=64, blank=True, null=True)
    provisioned = models.CharField(verbose_name='provisioned', max_length=64, blank=True, null=True)
    inuse = models.CharField(verbose_name='inuse', max_length=64, blank=True, null=True)
    unshared = models.CharField(verbose_name='unshared', max_length=64, blank=True, null=True)
    harestartpriority = models.CharField(verbose_name='harestartpriority', max_length=64, blank=True, null=True)
    haisolatinresponse = models.CharField(verbose_name='haisolatinresponse', max_length=64, blank=True, null=True)
    vmmonitoring = models.CharField(verbose_name='vmmonitoring', max_length=64, blank=True, null=True)
    clusterrule = models.CharField(verbose_name='clusterrule', max_length=64, blank=True, null=True)
    clusterrulename = models.CharField(verbose_name='clusterrulename', max_length=64, blank=True, null=True)
    bootrequired = models.CharField(verbose_name='bootrequired', max_length=64, blank=True, null=True)
    bootdelay =  models.CharField(verbose_name='bootdelay', max_length=64, blank=True, null=True)
    bootretrydelay = models.CharField(verbose_name='bootretrydelay', max_length=64, blank=True, null=True)
    bootretryenabled = models.CharField(verbose_name='bootretryenabled', max_length=64, blank=True, null=True)
    bootbios = models.CharField(verbose_name='bootretrydelay', max_length=64, blank=True, null=True)
    firmware = models.CharField(verbose_name='firmware', max_length=64, blank=True, null=True)
    hwversion = models.CharField(verbose_name='hwversion', max_length=64, blank=True, null=True)
    hwupgradestatus = models.CharField(verbose_name='hwupgradestatus', max_length=64, blank=True, null=True)
    hwupgradepolicy = models.CharField(verbose_name='hwupgradestatus', max_length=64, blank=True, null=True)
    hwtarget = models.CharField(verbose_name='hwtarget', max_length=64, blank=True, null=True)
    path = models.CharField(verbose_name='path', max_length=256, blank=True, null=True)
    logdir = models.CharField(verbose_name='logdir', max_length=256, blank=True, null=True)
    snapshotdir = models.CharField(verbose_name='snapshotdir', max_length=256, blank=True, null=True)
    suspenddir = models.CharField(verbose_name='suspenddir', max_length=256, blank=True, null=True)
    notes = models.CharField(verbose_name='notes', max_length=512, blank=True, null=True)
    backupstatus = models.CharField(verbose_name='backupstatus', max_length=256, blank=True, null=True)
    lastbackup = models.CharField(verbose_name='lastbackup', max_length=64, blank=True, null=True)
    datacenter = models.CharField(verbose_name='datacenter', max_length=64, blank=True, null=True)
    cluster = models.CharField(verbose_name='cluster', max_length=64, blank=True, null=True)
    host = models.CharField(verbose_name='host', max_length=64, blank=True, null=True)
    os = models.CharField(verbose_name='os', max_length=64, blank=True, null=True)
    ostools = models.CharField(verbose_name='ostools', max_length=64, blank=True, null=True)
    objectid = models.CharField(verbose_name='objectid', max_length=64, blank=True, null=True)
    vmuuid = models.CharField(verbose_name='vmuuid', max_length=64, blank=True, null=True)
    visdkservertype = models.CharField(verbose_name='visdkservertype', max_length=64, blank=True, null=True)
    visdkapi = models.CharField(verbose_name='visdkapi', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    vcenteruuid = models.CharField(verbose_name='vcenteruuid', max_length=64, blank=True, null=True)

# cluster
class vCluster(models.Model):
    clustername = models.CharField(verbose_name='clustername', max_length=64, blank=True, null=True)
    configstatus = models.CharField(verbose_name='configstatus', max_length=64, blank=True, null=True)
    overallstatus = models.CharField(verbose_name='overallstatus', max_length=64, blank=True, null=True)
    numhosts = models.CharField(verbose_name='numhosts', max_length=64, blank=True, null=True)
    numeffectivehosts = models.CharField(verbose_name='numeffectivehosts', max_length=64, blank=True, null=True)
    totalcpu = models.CharField(verbose_name='totalcpu', max_length=64, blank=True, null=True)
    numcpucores = models.CharField(verbose_name='numcpucores', max_length=64, blank=True, null=True)
    numcputhreads = models.CharField(verbose_name='numcputhreads', max_length=64, blank=True, null=True)
    effectivecpu = models.CharField(verbose_name='effectivecpu', max_length=64, blank=True, null=True)
    totalmemory = models.CharField(verbose_name='totalmemory', max_length=64, blank=True, null=True)
    effectivememory = models.CharField(verbose_name='effectivememory', max_length=64, blank=True, null=True)
    numvmotions = models.CharField(verbose_name='numvmotions', max_length=64, blank=True, null=True)
    haenabled = models.CharField(verbose_name='haenabled', max_length=64, blank=True, null=True)
    failoverlevel = models.CharField(verbose_name='failoverlevel', max_length=64, blank=True, null=True)
    admissioncontrolenabled = models.CharField(verbose_name='admissioncontrolenabled', max_length=64, blank=True, null=True)
    hostmonitoring = models.CharField(verbose_name='hostmonitoring', max_length=64, blank=True, null=True)
    HBDatastoreCandidatePolicy = models.CharField(verbose_name='HBDatastoreCandidatePolicy', max_length=64, blank=True, null=True)
    IsolationResponse = models.CharField(verbose_name='IsolationResponse', max_length=64, blank=True, null=True)
    RestartPriority = models.CharField(verbose_name='RestartPriority', max_length=64, blank=True, null=True)
    ClusterSettings = models.CharField(verbose_name='ClusterSettings', max_length=64, blank=True, null=True)
    MaxFailure = models.CharField(verbose_name='MaxFailure', max_length=64, blank=True, null=True)
    MaxFailureWin = models.CharField(verbose_name='MaxFailureWin', max_length=64, blank=True, null=True)
    FaliureInterval = models.CharField(verbose_name='FaliureInterval', max_length=64, blank=True, null=True)
    MinUpTime = models.CharField(verbose_name='MinUpTime', max_length=64, blank=True, null=True)
    VMMonitoring = models.CharField(verbose_name='VMMonitoring', max_length=64, blank=True, null=True)
    DRSenable = models.CharField(verbose_name='DRSenable', max_length=64, blank=True, null=True)
    DRSdefault = models.CharField(verbose_name='DRSdefault', max_length=64, blank=True, null=True)
    DRSvMotionRate = models.CharField(verbose_name='DRSvMotionRate', max_length=64, blank=True, null=True)
    DPMenable = models.CharField(verbose_name='DPMenable', max_length=64, blank=True, null=True)
    DPMdefault = models.CharField(verbose_name='DPMdefault', max_length=64, blank=True, null=True)
    DPMHostPower = models.CharField(verbose_name='DPMHostPower', max_length=64, blank=True, null=True)
    ObjectID = models.CharField(verbose_name='ObjectID', max_length=64, blank=True, null=True)
    visdkserver = models.CharField(verbose_name='visdkserver', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)

# vHost
class vHost(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    ConfigStatus = models.CharField(verbose_name='ConfigStatus', max_length=64, blank=True, null=True)
    MaintenanceMode = models.CharField(verbose_name='nMaintenanceMode', max_length=64, blank=True, null=True)
    QuarantineMode = models.CharField(verbose_name='QuarantineMode', max_length=64, blank=True, null=True)
    vSANFaultDomain = models.CharField(verbose_name='vSANFaultDomain', max_length=64, blank=True, null=True)
    CPUModel = models.CharField(verbose_name='CPUModel', max_length=64, blank=True, null=True)
    Speed = models.CharField(verbose_name='Speed', max_length=64, blank=True, null=True)
    HTAvailable = models.CharField(verbose_name='HTAvailable', max_length=64, blank=True, null=True)
    HTActive = models.CharField(verbose_name='HTActive', max_length=64, blank=True, null=True)
    CPU = models.CharField(verbose_name='CPU', max_length=64, blank=True, null=True)
    CoresPerCPU = models.CharField(verbose_name='CoresPerCPU', max_length=64, blank=True, null=True)
    Cores = models.CharField(verbose_name='Cores', max_length=64, blank=True, null=True)
    CPUusage = models.CharField(verbose_name='CPUusage', max_length=64, blank=True, null=True)
    Memory = models.CharField(verbose_name='Memory', max_length=64, blank=True, null=True)
    MemoryUsage = models.CharField(verbose_name='MemoryUsage', max_length=64, blank=True, null=True)
    Console = models.CharField(verbose_name='Console', max_length=64, blank=True, null=True)
    NICs = models.CharField(verbose_name='NICs', max_length=64, blank=True, null=True)
    HBAs = models.CharField(verbose_name='HBAs', max_length=64, blank=True, null=True)
    VMsTotal = models.CharField(verbose_name='VMsTotal', max_length=64, blank=True, null=True)
    VMs = models.CharField(verbose_name='VMs', max_length=64, blank=True, null=True)
    VMsPerCore = models.CharField(verbose_name='VMsPerCore', max_length=64, blank=True, null=True)
    vCPUs = models.CharField(verbose_name='vCPUs', max_length=64, blank=True, null=True)
    vCPUsPerCore = models.CharField(verbose_name='vCPUsPerCore', max_length=64, blank=True, null=True)
    vRAM = models.CharField(verbose_name='vRAM', max_length=64, blank=True, null=True)
    VMUsedMemory = models.CharField(verbose_name='VMUsedMemory', max_length=64, blank=True, null=True)
    VMMemorySwap = models.CharField(verbose_name='VMMemorySwap', max_length=64, blank=True, null=True)
    VMMemoryBallooned = models.CharField(verbose_name='VMMemoryBallooned', max_length=64, blank=True, null=True)
    VMotionSupport = models.CharField(verbose_name='VMotionSupport', max_length=64, blank=True, null=True)
    SVMotionSupport = models.CharField(verbose_name='SVMotionSupport', max_length=64, blank=True, null=True)
    CurrentEVC = models.CharField(verbose_name='CurrentEVC', max_length=64, blank=True, null=True)
    MaxEVC = models.CharField(verbose_name='MaxEVC', max_length=64, blank=True, null=True)
    assignedLicense = models.CharField(verbose_name='assignedLicense', max_length=64, blank=True, null=True)
    ATSHB = models.CharField(verbose_name='ATS', max_length=64, blank=True, null=True)
    ATSLock = models.CharField(verbose_name='ATSLock', max_length=64, blank=True, null=True)
    CPUPowerPolicy = models.CharField(verbose_name='CPUPowerPolicy', max_length=64, blank=True, null=True)
    SupportCPUPower = models.CharField(verbose_name='SupportCPUPower', max_length=64, blank=True, null=True)
    HostPowerPolicy = models.CharField(verbose_name='HostPowerPolicy', max_length=64, blank=True, null=True)
    ESXiVersion = models.CharField(verbose_name='ESXiVersion', max_length=64, blank=True, null=True)
    BootTime = models.CharField(verbose_name='BootTime', max_length=64, blank=True, null=True)
    DNSServer = models.CharField(verbose_name='DNSServer', max_length=64, blank=True, null=True)
    DHCP = models.CharField(verbose_name='DHCP', max_length=64, blank=True, null=True)
    Domain = models.CharField(verbose_name='Domain', max_length=64, blank=True, null=True)
    DNSSearch = models.CharField(verbose_name='DNSSearch', max_length=64, blank=True, null=True)
    NTP = models.CharField(verbose_name='NTP', max_length=64, blank=True, null=True)
    NTPDRunning = models.CharField(verbose_name='NTPDRunning', max_length=64, blank=True, null=True)
    TimeZone = models.CharField(verbose_name='TimeZone', max_length=64, blank=True, null=True)
    TimeZoneName = models.CharField(verbose_name='TimeZoneName', max_length=64, blank=True, null=True)
    GMTOffset = models.CharField(verbose_name='GMTOffset', max_length=64, blank=True, null=True)
    Vendor = models.CharField(verbose_name='Vendor', max_length=64, blank=True, null=True)
    Model = models.CharField(verbose_name='Model', max_length=64, blank=True, null=True)
    SerialNumber = models.CharField(verbose_name='SerialNumber', max_length=64, blank=True, null=True)
    ServiceTag = models.CharField(verbose_name='ServiceTag', max_length=64, blank=True, null=True)
    OEMString = models.CharField(verbose_name='OEMString', max_length=64, blank=True, null=True)
    BIOSVendor = models.CharField(verbose_name='BIOSVendor', max_length=64, blank=True, null=True)
    BIOSVersion = models.CharField(verbose_name='BIOSVersion', max_length=64, blank=True, null=True)
    BIOSDate = models.CharField(verbose_name='BIOSDate', max_length=64, blank=True, null=True)
    ObjectID = models.CharField(verbose_name='ObjectID', max_length=64, blank=True, null=True)
    AutoDeployMI = models.CharField(verbose_name='AutoDeployMI', max_length=64, blank=True, null=True)
    UUID = models.CharField(verbose_name='UUID', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='SVMotionSupport', max_length=64, blank=True, null=True)

# vNIC
class vNIC(models.Model):
    Host = models.CharField(verbose_name='Host', max_length=64, blank=True, null=True)
    Datacenter = models.CharField(verbose_name='Datacenter', max_length=64, blank=True, null=True)
    Cluster = models.CharField(verbose_name='Cluster', max_length=64, blank=True, null=True)
    NetworkDevice = models.CharField(verbose_name='NetworkDevice', max_length=64, blank=True, null=True)
    Driver = models.CharField(verbose_name='Driver', max_length=64, blank=True, null=True)
    Speed = models.CharField(verbose_name='Speed', max_length=64, blank=True, null=True)
    Duplex = models.CharField(verbose_name='Duplex', max_length=64, blank=True, null=True)
    MAC = models.CharField(verbose_name='MAC', max_length=64, blank=True, null=True)
    Switch = models.CharField(verbose_name='Switch', max_length=64, blank=True, null=True)
    UplinkPort = models.CharField(verbose_name='UplinkPort', max_length=64, blank=True, null=True)
    PCI = models.CharField(verbose_name='PCI', max_length=64, blank=True, null=True)
    WakeOn = models.CharField(verbose_name='WakeOn', max_length=64, blank=True, null=True)
    vcenter = models.CharField(verbose_name='vcenter', max_length=64, blank=True, null=True)
    visdkuuid = models.CharField(verbose_name='visdkuuid', max_length=64, blank=True, null=True)
