# Generated by Django 4.0.6 on 2022-07-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vHBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=64, null=True, verbose_name='Host')),
                ('datacenter', models.CharField(blank=True, max_length=64, null=True, verbose_name='Datacenter')),
                ('cluster', models.CharField(blank=True, max_length=64, null=True, verbose_name='Cluster')),
                ('device', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device')),
                ('type', models.CharField(blank=True, max_length=64, null=True, verbose_name='Type')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='Status')),
                ('bus', models.IntegerField(blank=True, null=True, verbose_name='Bus')),
                ('pci', models.CharField(blank=True, max_length=64, null=True, verbose_name='Pci')),
                ('driver', models.CharField(blank=True, max_length=64, null=True, verbose_name='Driver')),
                ('wwn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wwn')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('vi_sdk_server', models.CharField(blank=True, max_length=64, null=True, verbose_name='vCenter地址')),
                ('vi_sdk_uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='vCenter地址')),
            ],
        ),
        migrations.DeleteModel(
            name='VmInventory',
        ),
    ]
