# Generated by Django 4.0.6 on 2022-07-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvtools', '0002_vhba_delete_vminventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='vhba',
            name='vi_sdk_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='vCenter UUID'),
        ),
    ]
