# Generated by Django 4.1.7 on 2023-03-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvtools', '0053_enic_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcd',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vcd',
            name='LastBackup',
        ),
        migrations.RemoveField(
            model_name='vcpu',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vcpu',
            name='LastBackup',
        ),
        migrations.RemoveField(
            model_name='vdisk',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vdisk',
            name='LastBackup',
        ),
        migrations.RemoveField(
            model_name='vhost',
            name='AutoDeployMI',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='backupstatus',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='lastbackup',
        ),
        migrations.RemoveField(
            model_name='vmemory',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vmemory',
            name='LastBackup',
        ),
        migrations.RemoveField(
            model_name='vnetwork',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vnetwork',
            name='LastBackup',
        ),
        migrations.RemoveField(
            model_name='vpartition',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vpartition',
            name='LastBackup',
        ),
        migrations.RemoveField(
            model_name='vsnapshot',
            name='AppStatus',
        ),
        migrations.RemoveField(
            model_name='vsnapshot',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vsnapshot',
            name='LastBackup',
        ),
        migrations.RemoveField(
            model_name='vtools',
            name='BackupStatus',
        ),
        migrations.RemoveField(
            model_name='vtools',
            name='LastBackup',
        ),
        migrations.AlterField(
            model_name='fnic',
            name='NodeName',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='NodeName'),
        ),
    ]
